# Generated by Django 4.0 on 2024-01-21 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Academy',
        ),
        migrations.RemoveField(
            model_name='locationrecord',
            name='student',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
        migrations.DeleteModel(
            name='LocationRecord',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
